### ISSUE TITLE
Remove debugging statements in ring buffer source

### ISSUE THREAD

**Issue by fako1024** [fako1024/slimcap#6]
There are several debugging statements currently in place in the `nextPacket()` method of the ring buffer source used to check for buffer under-/overruns in the wild. Prior to release those should be removed.

DoD

- [x] Remove debugging statements
- [x] Check remaining TODOs in code
- [x] Consider keeping some (using regular logging facilities or other means)

**Comment by fako1024** [comment]
Added performance label since at the current (and future) level of optimization the additional checks performed for the debugging statements actually affect performance.

**Comment by fako1024** [comment]
@els0r Since you've already done some production-grade alpha testing in https://github.com/els0r/goProbe/issues/131 I was wondering if you could do a quick `grep` for the string `WUT` in the `goProbe` logs to see if there are any occurrences. I'd hope not, but who knows. Much traffic, many interfaces etc...

**Comment by els0r** [comment]
More qualitative than quantitive answer: spot checks didn't reveal any WUTs (they would have caught my eye).

I will pipe a longer running test into a log file and provide a more conclusive answer.
